### ISSUE TITLE
Please Fix Internal Resources

### ISSUE THREAD

**Issue by dusten** [Juniper/contrail-ansible-deployer#12]
Please remove all internal references from the wiki.

For example: ci-repo.englab.juniper.net:5000

**Comment by nitishkrishna** [comment]
Done

**Comment by marouim** [comment]
release-3.7-contrail  still refer to this : Fresh install 
[root@ocp-master ~]# oc get pods
NAME                                 READY     STATUS             RESTARTS   AGE
config-zookeeper-pvsdc               0/1       ImagePullBackOff   0          10m
contrail-analytics-jf7zf             0/7       ErrImagePull       0          10m
contrail-analytics-zookeeper-xjdm6   0/1       ImagePullBackOff   0          10m
contrail-analyticsdb-mv82n           0/1       ImagePullBackOff   0          10m
contrail-configdb-nnb2t              0/1       ImagePullBackOff   0          10m
contrail-controller-config-rbxdc     0/5       ImagePullBackOff   0          10m
contrail-controller-control-5s7wx    0/4       ImagePullBackOff   0          10m
contrail-controller-webui-ndccb      0/2       ImagePullBackOff   0          10m
contrail-kube-manager-h6jhz          0/1       ImagePullBackOff   0          10m
kafka-wsnd7                          0/1       ErrImagePull       0          10m
rabbitmq-28rgf                       0/1       ImagePullBackOff   0          10m
redis-pwvmb                          1/1       Running            0          10m


Example: 

Containers:
  zookeeper:
    Container ID:
    Image:		ci-repo.englab.juniper.net:5000/contrail-external-zookeeper:newton-5.0-40
