### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by coolpalani** [Juniper/contrail-ansible-deployer#5]
Hello,

Could you share the instructions for deploy Contrail and integrate with Kubernetes.

As per your examples, should we have  to install docker engine before our deploy 
192.168.1.100:
#      ansible_ssh_pass: contrail123
#    192.168.1.101:
#      ansible_ssh_pass: contrail123
#    192.168.1.102:
# ansible_ssh_pass: contrail

**Comment by michaelhenkel** [comment]
the procedure is currently being reworked. New extensive readme will be online Monday/Tuesday

**Comment by coolpalani** [comment]
I am eagerly looking your updates.

**Comment by nitishkrishna** [comment]
@coolpalani 
https://github.com/Juniper/contrail-ansible-deployer/wiki/Contrail-microservice-installation-with-kubernetes

**Comment by Andrey-mp** [comment]
@coolpalani is this issue fixed? please close it or comment.

**Comment by coolpalani** [comment]
I haven't tested yet. I will updated if anything else require
