### ISSUE TITLE
Integrate OpenContrail with Existing OpenStack

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [Juniper/contrail-ansible-deployer#7]
hi, there is any tutorial to integrate OpenContrail with existing openstack. i want to change my existing openstack controller to opencontrail. but i cant find any good tutorial to it? thanks before

**Comment by zufardhiyaulhaq** [comment]
im trying by installing only opencontrail with this tutorial

> provider_config:
>   bms:
>     ssh_pwd: btech
>     ssh_user: root
>     domainsuffix: local
> instances:
>   bms1:
>     provider: bms
>     ip: 10.90.90.10
>     roles:
>       config_database:
>       config:
>       control:
>       analytics_database:
>       analytics:
>       webui:
> contrail_configuration:
>   CONTRAIL_VERSION: latest
>   CONTROLLER_NODES: 10.90.90.10
>   CLOUD_ORCHESTRATOR: openstack
>   RABBITMQ_NODE_PORT: 5673
>   VROUTER_GATEWAY: 10.91.91.1
>   PHYSICAL_INTERFACE: eth1
>   KEYSTONE_AUTH_HOST: 10.90.90.10
>   KEYSTONE_AUTH_URL_VERSION: /v3
> kolla_config:
>   kolla_globals:
>     network_interface: "eth0"
>     enable_haproxy: "no"
>     enable_swift: "no"
>     enable_ironic: "no"
>     enable_ceilometer: "no"
>     enable_heat: "no"
>   kolla_passwords:
>     keystone_admin_password: rahasia
> 

and running this command
> ansible-playbook -i inventory/ playbooks/configure_instances.yml
> ansible-playbook -i inventory/ -e orchestrator=none playbooks/install_contrail.yml

i can open opencontrail web, but i dont know username and password to login.
i try with openstack env but it cant login

username : admin
password : rahasia

**Comment by Andrey-mp** [comment]
@zufardhiyaulhaq I don't see openstack role in your instances.yaml
If you to deploy OpenStack with Contrail then such role/roles must be there

**Comment by zufardhiyaulhaq** [comment]
hi @Andrey-mp, if im define openstack role, the script will install the openstack.
i want to integrate exisiting openstack with new contrail.

but now i have follow this tutorial, https://github.com/openstack/networking-opencontrail

**Comment by Andrey-mp** [comment]
Hi @zufardhiyaulhaq 
ansible-deployer doesn't claim that it can support contrail installation on top of current openstack.
because it can't control needed parts in neutron/nova/heat.

**Comment by srikandiduduk** [comment]
Hi @Andrey-mp do you mean if I built opencontrail using ansible deployer I cannot integrate with my existing Openstack ?

**Comment by Andrey-mp** [comment]
1. it's not so correct to say 'building opencontrail using ansible deployer'. it's not a 'building' - it's a 'deployyng'
2. then from item #1 ansible-deployer can't change/configure/setup existing openstack cause it doesn't have control for it

**Comment by srikandiduduk** [comment]
What if I Deploy the opencontrail using ansible and after the opencontrail deployed I change some script like this tutorial ?
https://github.com/Juniper/contrail-controller/wiki/Configuring-Contrail-for-OpenStack

**Comment by Andrey-mp** [comment]
This doc is four years old. It's not applicable to current version.
In theory it's possible to deploy Contrail with ansible-deployer (with endpoints of existing OpenStack in the settings). And then re-configure OpenStack to the Contrail setup.
But in fact there is no document how to do it.

**Comment by zufardhiyaulhaq** [comment]
can you share how to re-configure openstack to the contrail setup? its hard to understand @Andrey-mp

**Comment by Andrey-mp** [comment]
As I said - there is no doc for this case for R5.x.

In general you need to run all openstack-init related containers on openstack nodes and reconfigure neutron and heat.
It's implemented here https://github.com/Juniper/contrail-charms/tree/R5/contrail-openstack/hooks
in files contrail_openstack_hooks.py and contrail_openstack_utils.py
If you can read that code - you can do it manually.

**Comment by JannisHan** [comment]
I want to ask this a question, too. there is any tutorial to integrate OpenContrail with existing openstack, use the kolla deployment method.

**Comment by enjoy-freedom** [comment]
> im trying by installing only opencontrail with this tutorial
> 
> > provider_config:
> > bms:
> > ssh_pwd: btech
> > ssh_user: root
> > domainsuffix: local
> > instances:
> > bms1:
> > provider: bms
> > ip: 10.90.90.10
> > roles:
> > config_database:
> > config:
> > control:
> > analytics_database:
> > analytics:
> > webui:
> > contrail_configuration:
> > CONTRAIL_VERSION: latest
> > CONTROLLER_NODES: 10.90.90.10
> > CLOUD_ORCHESTRATOR: openstack
> > RABBITMQ_NODE_PORT: 5673
> > VROUTER_GATEWAY: 10.91.91.1
> > PHYSICAL_INTERFACE: eth1
> > KEYSTONE_AUTH_HOST: 10.90.90.10
> > KEYSTONE_AUTH_URL_VERSION: /v3
> > kolla_config:
> > kolla_globals:
> > network_interface: "eth0"
> > enable_haproxy: "no"
> > enable_swift: "no"
> > enable_ironic: "no"
> > enable_ceilometer: "no"
> > enable_heat: "no"
> > kolla_passwords:
> > keystone_admin_password: rahasia
> 
> and running this command
> 
> > ansible-playbook -i inventory/ playbooks/configure_instances.yml
> > ansible-playbook -i inventory/ -e orchestrator=none playbooks/install_contrail.yml
> 
> i can open opencontrail web, but i dont know username and password to login.
> i try with openstack env but it cant login
> 
> username : admin
> password : rahasia

I also encountered that the user and password of opencontrail could not log in,but I successfully logged in with openstack's user and password.I don't know why?

**Comment by enjoy-freedom** [comment]
I want to know if you have successfully deployed opencontract on the existing openstack.I would appreciate it if you could tell me how to do it

**Comment by hoangphuocbk** [comment]
https://object-storage-ca-ymq-1.vexxhost.net/swift/v1/6e4619c416ff4bd19e1c087f27a43eea/www-assets-prod/summits/27/presentations/23907/slides/TF-ML2-Shanghai-final-public.pdf

In this presentation, Sukhdev mentioned to migrate from ovs-based to tf-based compute. I think it can match your requirement.

**Comment by zufardhiyaulhaq** [comment]
I am closing this.
